"""Does stochastic scoring inflate the best-of-N maximum?

Our reproduction reaches a lower maximum than the paper reports on all eight
property sets. Before attributing that to anything about the model, one
mechanism has to be ruled out, and it is a purely statistical one.

The released notebook decodes the forward task with do_sample=True. So the R2
assigned to a candidate is itself a random variable: submit the same sequence
twice and you can get two different scores. When you then take the maximum over
N candidates, you are taking a maximum over N *noisy* scores, and that maximum
is inflated relative to the maximum over N noiseless scores by roughly the
scale of the scoring noise. We decode greedily (assumption A5), so our scores
carry no such noise and our maximum is correspondingly lower - through no
difference in the sequences generated.

This script isolates that effect exactly. It takes the candidate sequences
already generated by scripts/02_reproduce_table1.py and re-scores those same
sequences with the notebook's sampled forward decoder. Same sequences, same
targets, only the scoring changes. Any difference in the maximum is attributable
to scoring stochasticity and nothing else.

Usage:
    python scripts/10b_scoring_stochasticity.py --sets S1 F1 --limit 800
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from silkrepro import config, metrics, runinfo  # noqa: E402
from silkrepro.model import GenerationSettings, SilkomeGPT  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sets", nargs="*", default=["S1", "F1", "S4"])
    ap.add_argument("--limit", type=int, default=800,
                    help="candidates per set to re-score")
    ap.add_argument("--batch-size", type=int, default=16)
    ap.add_argument("--seed", type=int, default=config.SEED)
    args = ap.parse_args()

    model = SilkomeGPT()
    sampled = GenerationSettings.forward_notebook()
    print(f"re-scoring with the notebook's forward setting: {sampled.to_dict()}\n")

    rows = []
    for set_name in args.sets:
        p = config.RESULTS / "pools" / f"pool_{set_name}.csv"
        if not p.exists():
            print(f"{set_name}: no pool, skipping")
            continue
        pool = pd.read_csv(p)
        scored = pool[pool["forward_parsed"] & pool["novel_exact"]].copy()
        scored = scored[np.isfinite(scored["r2"])].head(args.limit)
        if scored.empty:
            continue

        target = config.ALL_SETS[set_name]
        seqs = scored["sequence"].astype(str).tolist()
        print(f"{set_name}: re-scoring {len(seqs)} candidates")

        preds = model.predict_properties_batch(
            seqs, settings=sampled, seed=args.seed, batch_size=args.batch_size
        )
        r2_sampled = np.array(
            [
                metrics.r2_within_vector(target, p) if p is not None else np.nan
                for p in preds
            ]
        )
        r2_greedy = scored["r2"].to_numpy(dtype=float)

        ok = np.isfinite(r2_sampled) & np.isfinite(r2_greedy)
        g, s = r2_greedy[ok], r2_sampled[ok]
        n_identical = int(np.sum(np.abs(g - s) < 1e-9))

        entry = {
            "set": set_name,
            "n": int(ok.sum()),
            "paper_r2": config.ALL_R2_PAPER[set_name],
            "max_greedy": float(g.max()),
            "max_sampled": float(s.max()),
            "max_inflation": float(s.max() - g.max()),
            "mean_greedy": float(g.mean()),
            "mean_sampled": float(s.mean()),
            "frac_scores_identical": n_identical / len(g),
            "gap_to_paper_greedy": float(config.ALL_R2_PAPER[set_name] - g.max()),
            "gap_to_paper_sampled": float(config.ALL_R2_PAPER[set_name] - s.max()),
        }
        rows.append(entry)
        print(f"  max greedy  {entry['max_greedy']:.4f}")
        print(f"  max sampled {entry['max_sampled']:.4f}  "
              f"(inflation {entry['max_inflation']:+.4f})")
        print(f"  paper       {entry['paper_r2']:.4f}  "
              f"(remaining gap {entry['gap_to_paper_sampled']:+.4f})")
        print(f"  scores identical on {entry['frac_scores_identical']:.1%} "
              f"of candidates\n")

    if not rows:
        raise SystemExit("no pools to re-score")

    df = pd.DataFrame(rows)
    df.to_csv(config.RESULTS / "scoring_stochasticity.csv", index=False)
    print(df.to_string(index=False, float_format=lambda x: f"{x:.4f}"))

    mean_infl = float(df["max_inflation"].mean())
    mean_gap = float(df["gap_to_paper_sampled"].mean())
    print(f"\nmean inflation of the maximum from stochastic scoring: {mean_infl:+.4f}")
    print(f"mean gap to the paper that remains after it:           {mean_gap:+.4f}")

    path = runinfo.write_result(
        "10b_scoring_stochasticity",
        {
            "per_set": rows,
            "mean_max_inflation": mean_infl,
            "mean_remaining_gap": mean_gap,
            "note": (
                "Same candidate sequences under both scorers; only the forward "
                "decoding differs. Any change in the maximum is attributable "
                "to scoring stochasticity."
            ),
        },
        script="scripts/10b_scoring_stochasticity.py",
        params={"sets": args.sets, "limit": args.limit, "seed": args.seed},
    )
    print(f"\nwrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
